version: '3'

# env:
#   WORD: World from Task
  
dotenv: ['.env']

tasks:
  helloworld:
    cmds:
      - echo "Hello $WORD!"
    env:
      GREETING: hello
      
  byeworld:
    cmds:
      - echo "$GREETING $WORD!"
    env:
      GREETING: Bye
  makefriend:
    cmds:
      - echo "Nice to meet you, Mate!"
    env:
      GREETING: Nice to meet you!          
      
  all:
    deps: [helloworld, byeworld, makefriend] 
